//! Native IDE host. JVM extension classes are generated by Rust at build time.
mod authoring;
mod editor;
mod feedback;
#[cfg(feature = "ide-tests")]
mod ide_tests;
pub mod jvm;
mod model;
pub mod process;
mod project;
pub mod protocol;
mod router;
mod run_configuration;
pub mod session;
mod source;
mod stability;
pub mod starter;
mod surface;
mod watcher;
mod wizard;
mod workspace;
use jni::{
    JNIEnv,
    objects::{JClass, JObject, JObjectArray, JString},
    sys::jobject,
};

/// Optional project features for plugins built from the reusable host.
/// Configure before the first JNI dispatch; the first configuration wins.
#[derive(Clone, Copy)]
pub struct HostFeatures {
    pub cargo: bool,
    pub stability: bool,
}
static FEATURES: std::sync::OnceLock<HostFeatures> = std::sync::OnceLock::new();
pub fn configure(features: HostFeatures) {
    let _ = FEATURES.set(features);
}
fn features() -> &'static HostFeatures {
    FEATURES.get_or_init(|| HostFeatures {
        cargo: true,
        stability: true,
    })
}
/// Return true when your plugin has handled the message.
pub type MessageHandler = for<'a> fn(&mut jvm::J<'a>, &jvm::O, &str, &str) -> anyhow::Result<bool>;
static MESSAGE_HANDLER: std::sync::OnceLock<MessageHandler> = std::sync::OnceLock::new();
pub fn set_message_handler(handler: MessageHandler) {
    let _ = MESSAGE_HANDLER.set(handler);
}

/// JNI owns every incoming reference for this call. Results are local references
/// in that same JNI frame; panics never cross the native ABI.
#[allow(non_snake_case)] // JNI entry name.
#[cfg_attr(not(feature = "host-library"), unsafe(no_mangle))]
pub extern "system" fn Java_dev_cranpose_rust_Native_call<'local>(
    env: JNIEnv<'local>,
    _class: JClass<'local>,
    operation: JString<'local>,
    receiver: JObject<'local>,
    arguments: JObjectArray<'local>,
) -> jobject {
    let mut j = jvm::J { env };
    let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(
        || -> anyhow::Result<jobject> {
            let operation: String = j.env.get_string(&operation)?.into();
            if operation.starts_with("Probe.") {
                return dispatch(&mut j.env, &operation, receiver, arguments)
                    .map(JObject::into_raw);
            }
            let receiver = j.global(receiver)?;
            let array = j.global(arguments)?;
            let args = j.elements(&array)?;
            let result = router::dispatch(&mut j, &operation, &receiver, &args);

            result.and_then(|value| Ok(j.env.new_local_ref(value)?.into_raw()))
        },
    ));
    match result {
        Ok(Ok(value)) => value,
        result => {
            let message = match result {
                Ok(Err(e)) => format!("{e:#}"),
                _ => "Rust IDE host panicked".into(),
            };
            if !j.env.exception_check().unwrap_or(true) {
                let _ = j.env.throw_new("java/lang/RuntimeException", message);
            }
            std::ptr::null_mut()
        }
    }
}
fn dispatch<'local>(
    env: &mut JNIEnv<'local>,
    operation: &str,
    _receiver: JObject<'local>,
    args: JObjectArray<'local>,
) -> anyhow::Result<JObject<'local>> {
    match operation {
        "Probe.echo" => Ok(env.get_object_array_element(&args, 0)?),
        "Probe.add" => {
            let a = env.get_object_array_element(&args, 0)?;
            let b = env.get_object_array_element(&args, 1)?;
            let a = env.call_method(a, "longValue", "()J", &[])?.j()?;
            let b = env.call_method(b, "longValue", "()J", &[])?.j()?;
            Ok(env
                .call_static_method(
                    "java/lang/Long",
                    "valueOf",
                    "(J)Ljava/lang/Long;",
                    &[jni::objects::JValue::Long(a + b)],
                )?
                .l()?)
        }
        "Probe.main" => {
            let probe = env.new_object("dev/cranpose/rust/Probe", "()V", &[])?;
            let text = env.new_string("Cranpose 🦀 Rust bridge")?;
            let echo = env
                .call_method(
                    &probe,
                    "echo",
                    "(Ljava/lang/String;)Ljava/lang/String;",
                    &[jni::objects::JValue::Object(&text)],
                )?
                .l()?;
            let echo = JString::from(echo);
            let echo: String = env.get_string(&echo)?.into();
            anyhow::ensure!(echo == "Cranpose 🦀 Rust bridge", "JNI string round trip");
            let sum = env
                .call_method(
                    &probe,
                    "add",
                    "(JJ)J",
                    &[
                        jni::objects::JValue::Long(40),
                        jni::objects::JValue::Long(2),
                    ],
                )?
                .j()?;
            anyhow::ensure!(sum == 42, "JNI wide integer round trip");
            println!("Rust-generated JVM bridge: class verification and native round trips passed");
            Ok(JObject::null())
        }
        _ => anyhow::bail!("Unrecognized native bridge operation: {operation}"),
    }
}
