[package]
name = "cranpose-template-host"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
name = "cranpose_ide_host"
crate-type = ["cdylib"]

[features]
ide-tests = ["cranpose-host/ide-tests"]

[dependencies]
cranpose-host = { package = "cranpose-ide-host", git = "https://github.com/samoylenkodmitry/cranpose-idea", rev = "486bd4b297e0b633920a720744e4b949711314a9", features = ["host-library"] }
jni = "0.21"
