[package]
name = "cranpose-template-host"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
name = "cranpose_ide_host"
crate-type = ["cdylib"]

[features]
ide-tests = ["cranpose-host/ide-tests"]

[dependencies]
cranpose-host = { package = "cranpose-ide-host", git = "https://github.com/samoylenkodmitry/cranpose-idea", rev = "4a9bcacc85ffc8bce9b0b834b09a7155f44509c8", features = ["host-library"] }
jni = "0.21"
