[package]
name = "cranpose-template-tools"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
anyhow = "1"
cranpose-ide-tools = { package = "xtask", git = "https://github.com/samoylenkodmitry/cranpose-idea", rev = "486bd4b297e0b633920a720744e4b949711314a9" }
