[package]
name = "cranpose-plugin-authoring-ui"
description = "Native Cranpose editor controls and decorations for IntelliJ plugins"
version.workspace = true
edition.workspace = true
license.workspace = true
[dependencies]
cranpose-plugin-authoring = { path = "../authoring" }
cranpose-animation = { version = "0.1.176", git = "https://github.com/samoylenkodmitry/Cranpose", rev = "283736c61e85486214ba0ef8b9ac813000b5055d" }
cranpose-plugin-ux = { path = "../ux" }
cranpose = { version = "0.1.176", git = "https://github.com/samoylenkodmitry/Cranpose", rev = "283736c61e85486214ba0ef8b9ac813000b5055d", features = ["embed"] }
cranpose-core = { version = "0.1.176", git = "https://github.com/samoylenkodmitry/Cranpose", rev = "283736c61e85486214ba0ef8b9ac813000b5055d" }
cranpose-ui-graphics = { version = "0.1.176", git = "https://github.com/samoylenkodmitry/Cranpose", rev = "283736c61e85486214ba0ef8b9ac813000b5055d" }
serde_json = "1"
[dev-dependencies]
naga = { version = "30", features = ["wgsl-in"] }
[lints]
workspace = true
