[package]
name = "cranpose-plugin-authoring-ui"
description = "Native Cranpose editor controls and decorations for IntelliJ plugins"
version.workspace = true
edition.workspace = true
license.workspace = true
[dependencies]
cranpose-plugin-authoring = { path = "../authoring" }
cranpose-animation = { version = "0.1.173", git = "https://github.com/samoylenkodmitry/Cranpose", rev = "631bf7ca9159c14a123191b71d893b6cc92d357c" }
cranpose-plugin-ux = { path = "../ux" }
cranpose = { version = "0.1.173", git = "https://github.com/samoylenkodmitry/Cranpose", rev = "631bf7ca9159c14a123191b71d893b6cc92d357c", features = ["embed"] }
cranpose-core = { version = "0.1.173", git = "https://github.com/samoylenkodmitry/Cranpose", rev = "631bf7ca9159c14a123191b71d893b6cc92d357c" }
cranpose-ui-graphics = { version = "0.1.173", git = "https://github.com/samoylenkodmitry/Cranpose", rev = "631bf7ca9159c14a123191b71d893b6cc92d357c" }
serde_json = "1"
[dev-dependencies]
naga = { version = "30", features = ["wgsl-in"] }
[lints]
workspace = true
