[package]
name = "cranpose-plugin-authoring-ui"
description = "Native Cranpose editor controls and decorations for IntelliJ plugins"
version.workspace = true
edition.workspace = true
license.workspace = true
[dependencies]
cranpose-plugin-authoring = { path = "../authoring" }
cranpose-animation = { version = "0.1.170", git = "https://github.com/samoylenkodmitry/Cranpose", rev = "9656ee2eff7e07374279205cefbc40f07f87ce93" }
cranpose-plugin-ux = { path = "../ux" }
cranpose = { version = "0.1.170", git = "https://github.com/samoylenkodmitry/Cranpose", rev = "9656ee2eff7e07374279205cefbc40f07f87ce93", features = ["embed"] }
cranpose-core = { version = "0.1.170", git = "https://github.com/samoylenkodmitry/Cranpose", rev = "9656ee2eff7e07374279205cefbc40f07f87ce93" }
cranpose-ui-graphics = { version = "0.1.170", git = "https://github.com/samoylenkodmitry/Cranpose", rev = "9656ee2eff7e07374279205cefbc40f07f87ce93" }
serde_json = "1"
[dev-dependencies]
naga = { version = "30", features = ["wgsl-in"] }
[lints]
workspace = true
